trigger:
- master
- features/*

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '3.0.100'
      includePreviewVersions: true
  - task: Bash@3
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.sh

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '3.0.100'
  - task: PowerShell@2
    displayName: 'Build Script'
    inputs:
      targetType: filePath
      filePath: ./build.ps1  
  - task: NuGetCommand@2
    displayName: 'Push package to Github'
    inputs:
      command: push
      packagesToPush: 'artifacts/*.nupkg'
      nuGetFeedType: external
      publishFeedCredentials: 'GitHub Packages'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))